### ISSUE TITLE
unhandled JS Exception: Module RCTLog is not a registered callable module.

### ISSUE THREAD

**Issue by buhe** [exponentjs/exponent#3] opened 2016-09-08 17:19 UTC
Very interesting project!

I follow the setup guide to build exponent and run iOS shell successful.

But , the shell app tell me ``` unhandled JS Exception: Module RCTLog is not a registered callable module.``` when i enter exp url .

Thanks

**Comment by buhe** [comment] 2016-09-08 17:20
![image](https://cloud.githubusercontent.com/assets/650753/18359240/90d8d0f0-762b-11e6-841c-fbad0bae3990.png)

**Comment by brentvatne** [comment] 2016-09-18 17:19
cc @terribleben

**Comment by buhe** [comment] 2016-09-19 02:03
I skip this problem by use product build.

**Comment by tiensonqin** [comment] 2016-09-22 03:22
Same problem.

**Comment by nikki93** [comment] 2016-10-04 00:23
@buhe @tiensonqin still working on a fix for this, but temporarily if you run the JS in non-dev mode it should not have this issue.

**Comment by terribleben** [comment] 2016-10-04 00:32
Hi! Sorry about this. It happens when your iOS client uses cached production JS while running as a developer, then tries to call RCTLog (which is only registered in dev mode). The best solution is to turn off caching, so your client always fetches dev exponent JS from your local packager.

To turn off caching:
- Type `dev menu` or `dm` in the iOS URL bar
- In the resulting menu, make sure the "Use kernel cache?" switch is off:

![image](https://cloud.githubusercontent.com/assets/1316332/19058806/3dd14e2e-898f-11e6-887e-cf951568dd7f.png)

This preference uses NSUserDefaults and will persist between launches of the app.

**Closed** 2016-10-30 16:13 UTC

**Comment by terribleben** [comment] 2018-01-22 20:34
Hi, the answer above is pretty old, and not relevant any more. Our tools will automatically disable caching if you're loading a project in development.

**Comment by JakeNolan** [comment] 2018-01-22 21:59
@terribleben Ah I see, well perhaps you can still help me get unstuck because I am still seeing that exception. I would try to implement the suggestion here: https://github.com/facebook/react-native/issues/8663 to basically add this "var RCTLog = require('RCTLog');" into the index.ios.js file.

 My problem with that is in the newer versions of expo we don't have that anymore. And when I try to throw it into App.js I get an error telling me that it should be listed in the project's dependencies. However I don't think thats what needs done bc it's not something I can get from npm, I don't think.

Other related details: I just detached to expokit to try and implement some firebase dynamic link functionality. I am attempting to use the following versions of things:

 Xcode Version 9.2 (9C40b)

    "expo": "22.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.0.tar.gz",

(though I have tried 16.0.0-beta.5 per the docs also, with the same results)

I have been following the developing with expokit documentation to a T, in my mind, but as I mentioned above when I try to run the xworkspace file in xcode I see a screen saying There was a problem running the app with the RCTLog is not a registered callable module message at the bottom and filling up the output window in Xcode.

Don't hesitate to request any additional info from me anytime of day. Help, advice, hints, or direction of any kind would be much appreciated I am ready to be unstuck :)

**Comment by arrygoo** [comment] 2018-05-17 17:58
Hmm I'm getting this error after updating to expo 24 :(

**Comment by JakeNolan** [comment] 2018-05-31 00:19
@arrygoo Sadly I don't remember the exact path out. But I can confirm that I don't have that line in my App.json file anywhere. I believe that the eventual resolution or at least onto the next error message was to upgrade my expo version, I believe that I went to 24 to advance. Are you also trying to work with react-native-firebase?
